version: '3'
services:
  mysql:
    image: 'mysql:5.7'
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: stationSki
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  # Spring Boot Application Service
  spring-app:
    image: ahmedbenabderrazak648/gestion-station-ski:1.0
    container_name: stationSki
    restart:  on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/stationSki?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    ports:
      - "8089:8089"
    depends_on:
      - mysql
volumes:
 db: