version: '3.3'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: stationSki
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    image: jihene1999/gestion-station-ski:1.0
    container_name: gestion-station-ski
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.servlet.context-path": "/api",
        "server.port": "8089",
        "spring.mvc.format.date": "yyyy-MM-dd",
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/stationSki?useSSL=false",
        "spring.datasource.username": "root",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update",
        "logging.level.root": "info",
        "logging.pattern.console": "%d{yyyy-MM-dd HH:mm:ss} - %-5level- %logger{45} - %msg %n"
      }'
    volumes:
      - .m2:/root/.m2
  prometheus:
    image: prom/prometheus
    container_name: prometheusjihene
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
      image: grafana/grafana
      container_name: grafanajihene
      restart: unless-stopped
      ports:
        - "3000:3000"
      depends_on:
        - prometheus
      volumes:
        - grafana-data:/var/lib/grafana
      networks:
        - monitoring


networks:
  monitoring:
    driver: bridge

volumes:
  db:
  grafana-data: